<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE roms [
<!ELEMENT roms (rom)+>
<!ENTITY deg "&#176;">
<!-- degree sign --><!ENTITY micro "&#181;">
<!-- micro sign --><!ELEMENT rom (romid , table+)>
<!ATTLIST rom base CDATA #IMPLIED>
<!ELEMENT romid (xmlid , internalidaddress , internalidstring , caseid? , ecuid , year , market , make , model , submodel , transmission , flashmethod? , memmodel , filesize , obsolete?)>
<!ELEMENT xmlid (#PCDATA)>
<!ELEMENT internalidaddress (#PCDATA)>
<!ELEMENT internalidstring (#PCDATA)>
<!ELEMENT caseid (#PCDATA)>
<!ELEMENT ecuid (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT market (#PCDATA)>
<!ELEMENT make (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT submodel (#PCDATA)>
<!ELEMENT transmission (#PCDATA)>
<!ELEMENT flashmethod (#PCDATA)>
<!ELEMENT memmodel (#PCDATA)>
<!ELEMENT filesize (#PCDATA)>
<!ELEMENT obsolete (#PCDATA)>
<!ELEMENT table (#PCDATA | scaling | table | description | data | state)*>
<!ATTLIST table type NMTOKENS #IMPLIED>
<!ATTLIST table name CDATA #IMPLIED>
<!ATTLIST table category CDATA #IMPLIED>
<!ATTLIST table storagetype CDATA #IMPLIED>
<!ATTLIST table endian (little | big) #IMPLIED>
<!ATTLIST table sizex CDATA #IMPLIED>
<!ATTLIST table sizey CDATA #IMPLIED>
<!ATTLIST table userlevel (1 | 2 | 3 | 4 | 5) #IMPLIED>
<!ATTLIST table logparam CDATA #IMPLIED>
<!ATTLIST table storageaddress CDATA #IMPLIED>
<!ELEMENT scaling EMPTY>
<!ATTLIST scaling units CDATA #REQUIRED>
<!ATTLIST scaling expression CDATA #REQUIRED>
<!ATTLIST scaling to_byte CDATA #REQUIRED>
<!ATTLIST scaling format CDATA #REQUIRED>
<!ATTLIST scaling fineincrement CDATA #REQUIRED>
<!ATTLIST scaling coarseincrement CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ATTLIST state name CDATA #REQUIRED>
<!ATTLIST state data CDATA #REQUIRED>
]>
<roms>
	<rom>
     <!--
v0.1 by pazi88
	- draft of MS45

v0.2
	- additions from ba114 and zarboz

v0.2.TJW
	- additions for 44560BO00 based on posts by Johny_B, Lambda1, diablospeed and A2Ls for other MS45 revisions
	
v0.3
	- Add addressess for 4570LO00
	- fix errors

	 In this BASE section define all the common table data and axis attributes.
     Leave out the ROM specific addresses. -->
		<romid>
			<xmlid>BMWMS45BASE</xmlid>
			<ecuid>1234567</ecuid>
			<year>2001-2006</year>
			<market>USDM</market>
			<make>BMW</make>
			<model>E46/E60/X5</model>
			<submodel>MS45</submodel>
			<transmission>MT/AT</transmission>
			<memmodel>SAK-C167CR-LM</memmodel>
			<filesize>1024kb</filesize>
		</romid>

<!--Misc switches & configuration values-->
		<table type="Switch" name="Manual deactivation of cat diagnosis inhibition condition" category="Configurations" sizey="1" userlevel="1">
			<state name="1 - Deactivated" data="01"/>
			<state name="0 - Activated" data="00"/>
			<description>You can turn off the cat diagnostics by changing this to 1 (lc_inh_cat_diag_man_deac)</description>
		</table>

		<table type="2D" name="Exhaust configuration" category="Configurations" storagetype="uint8" endian="little" sizey="1" userlevel="1">
			<scaling units="" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="1"/>
			<table type="Static Y Axis" name="Exhaust configuration" sizey="1">
				<data>c_conf_cat</data>
			</table>
			<description>You can set desired oxygen sensor configuration here</description>
		</table>

		<table type="2D" name="MIL configuration" category="Configurations" storagetype="uint8" endian="little" sizey="1" userlevel="1">
			<scaling units="" expression="x" to_byte="x" format="0" fineincrement="1" coarseincrement="1"/>
			<table type="Static Y Axis" name="MIL configuration" sizey="1">
				<data>c_conf_mil</data>
			</table>
			<description>You can set desired MIL lamp configuration here</description>
		</table>

		<table type="2D" name="Coolant temperature threshold for fast cut-off activation" category="Configurations" storagetype="uint8" sizey="1" userlevel="1">
			<scaling units="(째C)" expression="(x*0.75)-48" to_byte="(x+48)/0.75" format="0.00" fineincrement="1" coarseincrement="10"/>
			<table type="Static Y Axis" name="Coolant temperature" sizey="1">
				<data>c_tco_min_fcut_fast</data>
			</table>
			<description>c_tco_min_fcut_fast</description>
		</table>

<!--c_obd_state_1-->

		<table type="BitwiseSwitch" name="Misfire monitoring supported" category="OBD Readiness Configurations">
			<bit position ="0" name="Enabled"/>
			<description>c_obd_state_1 bit 0</description>
		</table>
		
		<table type="BitwiseSwitch" name="Fuel system monitoring supported" category="OBD Readiness Configurations">
			<bit position ="1" name="Enabled"/>
			<description>c_obd_state_1 bit 1</description>
		</table>
	
		<table type="BitwiseSwitch" name="Comprehensive component monitoring supported" category="OBD Readiness Configurations">
			<bit position ="2" name="Enabled"/>
			<description>c_obd_state_1 bit 2</description>
		</table>
	
		<table type="BitwiseSwitch" name="Misfire monitoring status" category="OBD Readiness Configurations">
			<bit position ="4" name="Enabled"/>
			<description>c_obd_state_1 bit 4</description>
		</table>
		
		<table type="BitwiseSwitch" name="Fuel system monitoring status" category="OBD Readiness Configurations">
			<bit position ="5" name="Enabled"/>
			<description>c_obd_state_1 bit 5</description>
		</table>
		
		<table type="BitwiseSwitch" name="Comprehensive component monitoring status" category="OBD Readiness Configurations">
			<bit position ="6" name="Enabled"/>
			<description>c_obd_state_1 bit 6</description>
		</table>
		
<!--c_obd_state_2-->
		
		<table type="BitwiseSwitch" name="Catalyst monitoring" category="OBD Readiness Configurations">
			<bit position ="0" name="Enabled"/>
			<description>c_obd_state_2 bit 0</description>
		</table>
		
		<table type="BitwiseSwitch" name="Heated catalyst" category="OBD Readiness Configurations">
			<bit position ="1" name="Enabled"/>
			<description>c_obd_state_2 bit 1</description>
		</table>
	
		<table type="BitwiseSwitch" name="Evaporative system monitoring" category="OBD Readiness Configurations">
			<bit position ="2" name="Enabled"/>
			<description>c_obd_state_2 bit 2</description>
		</table>
	
		<table type="BitwiseSwitch" name="Secondary air system monitoring" category="OBD Readiness Configurations">
			<bit position ="3" name="Enabled"/>
			<description>c_obd_state_2 bit 3</description>
		</table>
	
		<table type="BitwiseSwitch" name="A/C system refrigerant monitoring" category="OBD Readiness Configurations">
			<bit position ="4" name="Enabled"/>
			<description>c_obd_state_2 bit 4</description>
		</table>
		
		<table type="BitwiseSwitch" name="Oxygen sensor monitoring" category="OBD Readiness Configurations">
			<bit position ="5" name="Enabled"/>
			<description>c_obd_state_2 bit 5</description>
		</table>
		
		<table type="BitwiseSwitch" name="Oxygen sensor heater monitoring" category="OBD Readiness Configurations">
			<bit position ="6" name="Enabled"/>
			<description>c_obd_state_2 bit 6</description>
		</table>
		
		<table type="BitwiseSwitch" name="EGR system monitoring" category="OBD Readiness Configurations">
			<bit position ="7" name="Enabled"/>
			<description>c_obd_state_2 bit 7</description>
		</table>
		
<!--Secondary Air Pump-->

		<table type="Switch" name="SAP autolearning" category="Secondary Air Pump" sizey="1" userlevel="1">
			<state name="1 - Deactivated" data="01"/>
			<state name="0 - Activated" data="00"/>
			<description>Parameter to turn off the autolearning of SAP. However if disabled, this forces LV_SAP to 1, meaning it turns ON the SAP. (lc_sap_det_di)</description>
		</table>

<!--Ignition Tables-->
		<table type="3D" name="Basic ignition angle for RON 98" category="Ignition" storagetype="uint8" endian="little" sizex="16" sizey="20" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*.375)-35.625" to_byte="(x+35.625)/.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="MAF Load" storagetype="uint16" endian="big" logparam="E2">
				<scaling units="mg/stroke" expression="x*.0212" to_byte="x/.0212" format="#" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_iga_bas_ron_98__n__maf</description>
		</table>

		<table type="3D" name="Basic ignition angle for RON 91" category="Ignition" storagetype="uint8" endian="little" sizex="16" sizey="20" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*.375)-35.625" to_byte="(x+35.625)/.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="MAF Load" storagetype="uint16" endian="big" logparam="E2">
				<scaling units="mg/stroke" expression="x*.0212" to_byte="x/.0212" format="#" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_iga_bas_ron_91__n__maf</description>
		</table>

		<table type="3D" name="Basic ignition angle IVVT Passive" category="Ignition" storagetype="uint8" endian="little" sizex="16" sizey="20" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*.375)-35.625" to_byte="(x+35.625)/.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="MAF Load" storagetype="uint16" endian="big" logparam="E2">
				<scaling units="mg/stroke" expression="x*.0212" to_byte="x/.0212" format="#" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_iga_bas__n__maf</description>
		</table>

		<table type="3D" name="Basic ignition angle offset VO Min" category="Ignition" storagetype="uint8" endian="little" sizex="16" sizey="20" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*.375)-35.625" to_byte="(x+35.625)/.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="MAF Load" storagetype="uint16" endian="big" logparam="E2">
				<scaling units="mg/stroke" expression="x*.0212" to_byte="x/.0212" format="#" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_iga_bas_add_min__ivvt__n__maf</description>
		</table>

		<table type="3D" name="Basic ignition angle offset VO Max" category="Ignition" storagetype="uint8" endian="little" sizex="16" sizey="20" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*.375)-35.625" to_byte="(x+35.625)/.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="MAF Load" storagetype="uint16" endian="big" logparam="E2">
				<scaling units="mg/stroke" expression="x*.0212" to_byte="x/.0212" format="#" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_iga_bas_add_max__ivvt__n__maf</description>
		</table>

<!--VANOS tables-->
		<table type="3D" name="Intake VANOS target - Cold Engine" category="VANOS" storagetype="uint8" endian="little" sizex="12" sizey="16" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*0.375)+60" to_byte="(x-60)/0.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="MAF Load" storagetype="uint16" endian="big" logparam="E2">
				<scaling units="mg/stroke" expression="x*.0212" to_byte="x/.0212" format="#" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_cam_sp_1_in_pl__n__maf_ivvt</description>
		</table>

		<table type="3D" name="Exhaust VANOS target - Cold Engine" category="VANOS" storagetype="uint8" endian="little" sizex="12" sizey="16" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*-0.375)-40" to_byte="(x+40)/-0.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="MAF Load" storagetype="uint16" endian="big" logparam="E2">
				<scaling units="mg/stroke" expression="x*.0212" to_byte="x/.0212" format="#" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_cam_sp_1_ex_pl__n__maf_ivvt</description>
		</table>

		<table type="3D" name="Intake VANOS target - Warm Engine" category="VANOS" storagetype="uint8" endian="little" sizex="12" sizey="16" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*0.375)+60" to_byte="(x-60)/0.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="MAF Load" storagetype="uint16" endian="big" logparam="E2">
				<scaling units="mg/stroke" expression="x*.0212" to_byte="x/.0212" format="#" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_cam_sp_2_in_pl__n__maf_ivvt</description>
		</table>

		<table type="3D" name="Exhaust VANOS target - Warm Engine" category="VANOS" storagetype="uint8" endian="little" sizex="12" sizey="16" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*-0.375)-40" to_byte="(x+40)/-0.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="MAF Load" storagetype="uint16" endian="big" logparam="E2">
				<scaling units="mg/stroke" expression="x*.0212" to_byte="x/.0212" format="#" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_cam_sp_2_ex_pl__n__maf_ivvt</description>
		</table>
		
		<table type="3D" name="Exhaust VANOS target - Idle Speed, Cold Engine" category="VANOS" storagetype="uint8" endian="little" sizex="6" sizey="6" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*-0.375)-40" to_byte="(x+40)/-0.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="MAF Load" storagetype="uint16" endian="big" logparam="E2">
				<scaling units="mg/stroke" expression="x*.0212" to_byte="x/.0212" format="#" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_cam_sp_1_ex_is__n__maf_ivvt</description>
		</table>
		
		<table type="3D" name="Intake VANOS target - Idle Speed, Cold Engine" category="VANOS" storagetype="uint8" endian="little" sizex="6" sizey="6" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*0.375)+60" to_byte="(x-60)/0.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="MAF Load" storagetype="uint16" endian="big" logparam="E2">
				<scaling units="mg/stroke" expression="x*.0212" to_byte="x/.0212" format="#" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_cam_sp_1_in_is__n__maf_ivvt</description>
		</table>
		
		<table type="3D" name="Exhaust VANOS target - Idle Speed, Warm Engine" category="VANOS" storagetype="uint8" endian="little" sizex="6" sizey="6" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*-0.375)-40" to_byte="(x+40)/-0.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="MAF Load" storagetype="uint16" endian="big" logparam="E2">
				<scaling units="mg/stroke" expression="x*.0212" to_byte="x/.0212" format="#" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_cam_sp_2_ex_is__n__maf_ivvt</description>
		</table>
		
		<table type="3D" name="Intake VANOS target - Idle Speed, Warm Engine" category="VANOS" storagetype="uint8" endian="little" sizex="6" sizey="6" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*0.375)+60" to_byte="(x-60)/0.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="MAF Load" storagetype="uint16" endian="big" logparam="E2">
				<scaling units="mg/stroke" expression="x*.0212" to_byte="x/.0212" format="#" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_cam_sp_2_in_is__n__maf_ivvt</description>
		</table>

		<table type="2D" name="Exhaust VANOS target - Full Load, Cold Engine" category="VANOS" storagetype="uint8" sizex="16" endian="little" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*-0.375)-40" to_byte="(x+40)/-0.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_cam_sp_1_ex_fl__n</description>
		</table>

		<table type="2D" name="Intake VANOS target - Full Load, Cold Engine" category="VANOS" storagetype="uint8" sizex="16" endian="little" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*0.375)+60" to_byte="(x-60)/0.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_cam_sp_1_in_fl__n</description>
		</table>

		<table type="2D" name="Exhaust VANOS target - Full Load, Warm Engine" category="VANOS" storagetype="uint8" sizex="16" endian="little" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*-0.375)-40" to_byte="(x+40)/-0.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_cam_sp_2_ex_fl__n</description>
		</table>

		<table type="2D" name="Intake VANOS target - Full Load, Warm Engine" category="VANOS" storagetype="uint8" sizex="16" endian="little" userlevel="1">
			<scaling units="(째) BTDC" expression="(x*0.375)+60" to_byte="(x-60)/0.375" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Engine Speed" storagetype="uint16" endian="big" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_cam_sp_2_in_fl__n</description>
		</table>

<!--Fuel Tables-->
		<table type="3D" name="Basic Lambda Setpoint - Bank 1" category="Fuel" storagetype="uint16" endian="big" sizex="8" sizey="8" userlevel="1">
			<scaling units="Lambda" expression="x*0.000061" to_byte="x/0.000061" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="MAF Load" storagetype="uint16" endian="big" logparam="E2">
				<scaling units="mg/stroke" expression="x*.0212" to_byte="x/.0212" format="#" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="big" logparam="P8">
				<scaling units="RPM" expression="x*32" to_byte="x/32" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_lamb_bas_1</description>
		</table>

		<table type="3D" name="Basic Lambda Setpoint - Bank 2" category="Fuel" storagetype="uint16" endian="big" sizex="8" sizey="8" userlevel="1">
			<scaling units="Lambda" expression="x*0.000061" to_byte="x/0.000061" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="MAF Load" storagetype="uint16" endian="big" logparam="E2">
				<scaling units="mg/stroke" expression="x*.0212" to_byte="x/.0212" format="#" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint8" endian="big" logparam="P8">
				<scaling units="RPM" expression="x*32" to_byte="x/32" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_lamb_bas_2</description>
		</table>

		<table type="2D" name="Full load lambda enrichment" category="Fuel" storagetype="uint16" endian="big" sizex="12" userlevel="1">
			<scaling units="Lambda" expression="x*0.000977" to_byte="x/0.000977" format="0.0000" fineincrement=".01" coarseincrement=".1"/>
			<table type="X Axis" name="Engine Speed" storagetype="uint8" endian="big" logparam="P8">
				<scaling units="RPM" expression="x*32" to_byte="x/32" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
			<description>ip_lamb_fl__n</description>
		</table>

		<table type="2D" name="Global injection time correction (ALL)" category="Fuel" storagetype="uint8" sizex="1" endian="little" userlevel="1">
			<scaling category="Metric" units="Multiplicative Factor" expression="x*0.0078125491" to_byte="x/0.0078125491" format="0.00" fineincrement=".01" coarseincrement=".1"/>
			<table type="Static Y Axis" name="Columns" sizex="1">
				<data>ALL</data>
			</table>
			<description>This multiplier can be used to adjust fueling for different size injectors or different fuel (c_ti_as).</description>
		</table>

		<table type="2D" name="Global injection time correction" category="Fuel" storagetype="uint8" sizex="6" endian="little" userlevel="1">
			<scaling category="Metric" units="Multiplicative Factor" expression="x*0.0078125491" to_byte="x/0.0078125491" format="0.00" fineincrement=".01" coarseincrement=".1"/>
			<table type="Static X Axis" name="Columns" sizex="6">
				<data>Cyl 1</data>
				<data>Cyl 5</data>
				<data>Cyl 3</data>
				<data>Cyl 6</data>
				<data>Cyl 2</data>
				<data>Cyl 4</data>
			</table>
			<description>These multipliers can be used to adjust fueling for different size injectors or different fuel. For example put 1.3 for e85 (c_ti_as_cyl[x]).</description>
		</table>

		<table type="2D" name="Minimum Injection Time" category="Fuel" storagetype="uint16" sizex="1" endian="big" userlevel="1">
			<scaling units="Injector Pulsewidth (milliseconds)" expression="x/250" to_byte="x*250" format="0.000" fineincrement=".01" coarseincrement=".1"/>
			<table type="Static Y Axis" sizex="1">
				<data>ALL</data>
			</table>
			<description>This table adjust the minimum injection time, important to change when adding larger injectors (c_ti_min).</description>
		</table>

		<table type="3D" name="Injector dead time correction" category="Fuel" storagetype="uint16" endian="big" sizex="6" sizey="8" userlevel="1">
			<scaling units="Injector pulsewidth (milliseconds)" expression="(x*0.004)-131.072" to_byte="(x+131.072)/0.004" format="0.000" fineincrement=".01" coarseincrement=".1"/>
			<table type="X Axis" name="Fuel pressure" storagetype="uint16" endian="big">
				<scaling units="hPa" expression="x*2.653361" to_byte="x/2.653361" format="0.000" fineincrement=".01" coarseincrement="1"/>
			</table>
			<table type="Y Axis" name="Battery voltage" storagetype="uint8" endian="big">
				<scaling units="Volts" expression="x*.101961" to_byte="x/.101961" format="0.000" fineincrement=".01" coarseincrement=".1"/>
			</table>
			<description>ip_ti_add_dly</description>
		</table>
		
		<table type="2D" name="Fuel mass flow to injection time - Bank 1" category="Fuel" storagetype="uint16" sizex="1" endian="big" userlevel="1">
			<scaling units="ms/(mg/stk)" expression="x*0.000006" to_byte="x/0.000006" format="0.000" fineincrement=".001" coarseincrement=".01"/>
			<table type="Static X Axis" sizex="1">
				<data>mff to ti</data>
			</table>
			<description>Injectionvalve characteristic for fuel mass flow to injection time at standard conditions (c_fac_mff_ti_stnd_1).</description>
		</table>
		
		<table type="2D" name="Fuel mass flow to injection time - Bank 2" category="Fuel" storagetype="uint16" sizex="1" endian="big" userlevel="1">
			<scaling units="ms/(mg/stk)" expression="x*0.000006" to_byte="x/0.000006" format="0.000" fineincrement=".001" coarseincrement=".01"/>
			<table type="Static X Axis" sizex="1">
				<data>mff to ti</data>
			</table>
			<description>Injectionvalve characteristic for fuel mass flow to injection time at standard conditions (c_fac_mff_ti_stnd_2).</description>
		</table>
		
		<table type="2D" name="Stoichiometric air to fuel ratio" category="Fuel" storagetype="uint16" sizex="1" endian="big" userlevel="1">
			<scaling units="AFR" expression="1/(x*0.00000193)" to_byte="(1/x)/0.00000193" format="0.0" fineincrement=".01" coarseincrement=".1"/>
			<table type="Static X Axis" sizex="1">
				<data>Stoich</data>
			</table>
			<description>Stoichiometric air fuel ratio (c_mff_fac). Orginal conversion is X*0.000001907 to get constant for stoichiometric air/fuel ratio. But in this form, you can put AFR value directly.</description>
		</table>

<!--Fuel Trims-->
		<table type="2D" name="Minimum value for adaptive additive factor for injection" category="Fuel trims" storagetype="uint16" sizex="1" endian="big" userlevel="1">
			<scaling units="mg/stroke (???)" expression="(x-65535)*.021194" to_byte="(x/.021194)+65535" format="0.000" fineincrement="0.01" coarseincrement="0.1"/>
			<table type="Static Y Axis" name="Columns" sizex="1">
				<data></data>
			</table>
			<description>c_mff_ad_add_min</description>
		</table>

		<table type="2D" name="Maximum value for adaptive additive factor for injection" category="Fuel trims" storagetype="uint16" sizex="1" endian="big" userlevel="1">
			<scaling units="mg/stroke (???)" expression="x*.021194" to_byte="x/.021194" format="0.000" fineincrement="0.01" coarseincrement="0.1"/>
			<table type="Static Y Axis" name="Columns" sizex="1">
				<data></data>
			</table>
			<description>c_mff_ad_add_max</description>
		</table>

		<table type="2D" name="Minimum value for adaptive multiplicative factor for injection at lower area" category="Fuel trims" storagetype="uint16" sizex="1" endian="big" userlevel="1">
			<scaling units="%" expression="(x*.001526)-100" to_byte="(x+100)/.001526" format="0.000" fineincrement="0.1" coarseincrement="1"/>
			<table type="Static Y Axis" name="Columns" sizex="1">
				<data></data>
			</table>
			<description>c_mff_ad_fac_l_min</description>
		</table>

		<table type="2D" name="Maximum value for adaptive multiplicative factor for injection at lower area" category="Fuel trims" storagetype="uint16" sizex="1" endian="big" userlevel="1">
			<scaling units="%" expression="x*.001526" to_byte="x/.001526" format="0.000" fineincrement="0.1" coarseincrement="1"/>
			<table type="Static Y Axis" name="Columns" sizex="1">
				<data></data>
			</table>
			<description>c_mff_ad_fac_l_max</description>
		</table>

		<table type="2D" name="Minimum value for adaptive multiplicative factor for injection at higher area" category="Fuel trims" storagetype="uint16" sizex="1" endian="big" userlevel="1">
			<scaling units="%" expression="(x*.001526)-100" to_byte="(x+100)/.001526" format="0.000" fineincrement="0.1" coarseincrement="1"/>
			<table type="Static Y Axis" name="Columns" sizex="1">
				<data></data>
			</table>
			<description>c_mff_ad_fac_h_min</description>
		</table>

		<table type="2D" name="Maximum value for adaptive multiplicative factor for injection at higher area" category="Fuel trims" storagetype="uint16" sizex="1" endian="big" userlevel="1">
			<scaling units="%" expression="x*.001526" to_byte="x/.001526" format="0.000" fineincrement="0.1" coarseincrement="1"/>
			<table type="Static Y Axis" name="Columns" sizex="1">
				<data></data>
			</table>
			<description>c_mff_ad_fac_h_max</description>
		</table>

		<table type="2D" name="Maximum engine speed for additive adaptation value calculation" category="Fuel trims" storagetype="uint8" sizex="1" endian="big" userlevel="1">
			<scaling units="RPM" expression="x*32" to_byte="x/32" format="#" fineincrement="50" coarseincrement="100"/>
			<table type="Static Y Axis" name="Columns" sizex="1">
				<data></data>
			</table>
			<description>c_n_mff_ad_add_max</description>
		</table>

		<table type="2D" name="Minimum engine speed for multiplicative adaptation value calculation at lower area" category="Fuel trims" storagetype="uint8" sizex="1" endian="big" userlevel="1">